name: User Story
description: Create a new user story to describe a feature or requirement from an end-user perspective.
title: "As a [role] I want [objective] for [motivation]"
labels: ["userstory"]
body:
  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      description: "Describe the feature from the user's perspective using the format: 'As a [user type], I want to [goal] so that [reason].'"
      placeholder: "As a [user type], I want to [goal] so that [reason]."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How critical is this user story?"
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define the conditions that must be met for this user story to be considered complete."
      placeholder: |
        - Given [some context], when [action happens], then [expected outcome].
        - The feature should function correctly under [specific condition].
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List any dependencies (e.g., other features, APIs, services) required for this user story to be completed."
      placeholder: "- Dependent on API endpoint X"
    validations:
      required: false

  - type: textarea
    id: non_functional_requirements
    attributes:
      label: "Non-Functional Requirements"
      description: "List any non-functional requirements that should be met (e.g., performance, security, scalability)."
      placeholder: |
        - Must load within 500ms
        - Should work on mobile and desktop
        - Should comply with accessibility guidelines
    validations:
      required: false

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: "Definition of Done"
      description: "Check when the user story is considered complete."
      options:
        - label: "Acceptance criteria met"
          required: true
        - label: "All necessary tests (unit, integration, e2e) have passed"
          required: true
        - label: "Code reviewed and merged"
          required: true
        - label: "Deployed to the appropriate environment"
          required: false

  - type: textarea
    id: resources
    attributes:
      label: "Resources"
      description: "Provide any relevant links, documentation, or designs (one per line)."
      placeholder: |
        - [API Docs](https://localhost:7189/swagger/index.html#/)
        - [Dribbble](https://dribbble.com/)
    validations:
      required: false
